# Libraies and Data Sheet Lord #

In [15]:
import pandas as pd 
import pickle
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor

### Data Set Lord ###
df=pd.read_csv('laptop_data.csv')
### Check data ##
df.head(5)

  Company            CPU   Ram    Storage       OpSys  Weight   Price
0      HP  Intel Core i5   8GB  256GB SSD  Windows 11    1.69  185000
1    Asus    AMD Ryzen 7  16GB  512GB SSD  Windows 11    2.20  295000
2    Dell  Intel Core i3   4GB    1TB HDD  Windows 10    2.18  135000
3  Lenovo  Intel Core i5   8GB  512GB SSD       No OS    1.70  175000
4   Apple             M2   8GB  256GB SSD       macOS    1.24  340000

# Data Cleaning #

In [6]:
## Ram line "Gb" Remove conver Integer ##
df['Ram']= df['Ram'].str.replace('GB','').astype(int)
df.head(5)  ##cheking##

  Company            CPU  Ram    Storage       OpSys  Weight   Price
0      HP  Intel Core i5    8  256GB SSD  Windows 11    1.69  185000
1    Asus    AMD Ryzen 7   16  512GB SSD  Windows 11    2.20  295000
2    Dell  Intel Core i3    4    1TB HDD  Windows 10    2.18  135000
3  Lenovo  Intel Core i5    8  512GB SSD       No OS    1.70  175000
4   Apple             M2    8  256GB SSD       macOS    1.24  340000

# Train /Test spilit Separate  Features (X) and Target (y) #

In [16]:
X = df[['Company','CPU','Ram','Storage','OpSys','Weight']]
y = df['Price']

## Saparate two  Data  Parts ##
X_train,X_test, y_train,y_test = train_test_split(X,y,test_size=0.15,random_state=42)
print(f"Training data row: {len(X_train)}, Testing data row:{(X_test)}")

Training data row: 53, Testing data row:   Company            CPU   Ram    Storage       OpSys  Weight
61      HP  Intel Core i3   8GB  512GB SSD       No OS    1.55
57    Acer  Intel Core i5  16GB  512GB SSD  Windows 11    1.80
0       HP  Intel Core i5   8GB  256GB SSD  Windows 11    1.69
43    Asus    AMD Ryzen 3   4GB  256GB SSD  Windows 11    1.55
5       HP    AMD Ryzen 5   8GB  512GB SSD  Windows 11    1.75
36    Dell  Intel Core i7   8GB  512GB SSD  Windows 11    1.75
16      HP  Intel Core i5  16GB  512GB SSD  Windows 11    1.70
12      HP  Intel Core i7  16GB    1TB SSD  Windows 11    1.54
25    Dell  Intel Core i5   8GB  256GB SSD  Windows 11    1.70
60    Asus    AMD Ryzen 5  16GB  512GB SSD  Windows 11    1.65

# Create Ml Pipeline and Model Train #

In [13]:
# Categorical  identify and transform #
categorical_features = ['Company','CPU','Ram','Storage','OpSys']
preprocessor= ColumnTransformer(
    transformers=[
        ('col_tnf',OneHotEncoder(sparse_output=False, drop='first',handle_unknown='ignore'),categorical_features) 
    ],
    remainder='passthrough'
)

# Create Random Forest Model With Pipeline #
model=RandomForestRegressor(n_estimators=100,random_state=42)
pipe=Pipeline([
    ('step1',preprocessor),
    ('step2',model)
])

# Train model #
pipe.fit(X_train,y_train)

print("✅ Model Trained Successfully!")
print(f"📈 Training Accuracy (R2 Score): {pipe.score(X_train, y_train):.2f}")

✅ Model Trained Successfully!
📈 Training Accuracy (R2 Score): 0.98

# Model Save pickel file #

In [14]:
with open('laptop_pipe.pkl','wb')as f:
    pickle.dump(pipe,f)
print("💾 Model saved as 'laptop_pipe.pkl'")

💾 Model saved as 'laptop_pipe.pkl'